"""Second migration

Revision ID: 99d87573c9e7
Revises: 1c3791671475
Create Date: 2023-02-27 16:05:59.673626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d87573c9e7'
down_revision = '1c3791671475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activityDate', sa.Date(), nullable=False),
    sa.Column('activityTime', sa.Integer(), nullable=False),
    sa.Column('activityDuration', sa.Integer(), nullable=False),
    sa.Column('activityFull', sa.Boolean(), nullable=False),
    sa.Column('activityCurrent', sa.Integer(), nullable=True),
    sa.Column('activityId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activityType', sa.String(length=250), nullable=True),
    sa.Column('activityPrice', sa.Float(), nullable=True),
    sa.Column('activityLocation', sa.String(length=250), nullable=True),
    sa.Column('activityCapacity', sa.Integer(), nullable=True),
    sa.Column('activityStaffName', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activityType')
    )
    op.create_table('user_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('calendarId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bookings')
    op.drop_table('sport')
    op.drop_table('calendar')
    # ### end Alembic commands ###
