"""empty message

Revision ID: cd8caed72d79
Revises: 99d87573c9e7
Create Date: 2023-02-27 18:37:18.421652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8caed72d79'
down_revision = '99d87573c9e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activityType', sa.String(length=250), nullable=True),
    sa.Column('activityPrice', sa.Float(), nullable=True),
    sa.Column('activityLocation', sa.String(length=250), nullable=True),
    sa.Column('activityCapacity', sa.Integer(), nullable=True),
    sa.Column('activityStaffName', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activityType')
    )
    op.drop_table('sport')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('activityType', sa.VARCHAR(length=250), nullable=True),
    sa.Column('activityPrice', sa.FLOAT(), nullable=True),
    sa.Column('activityLocation', sa.VARCHAR(length=250), nullable=True),
    sa.Column('activityCapacity', sa.INTEGER(), nullable=True),
    sa.Column('activityStaffName', sa.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activityType')
    )
    op.drop_table('activity')
    # ### end Alembic commands ###
